### ISSUE TITLE
Problem Inputs

### ISSUE THREAD

**Issue by zchrykng** [betaveros/advent-of-code-2022#1]
Howdy! Love how compact your solutions are. Just wanted to pass along an FYI that someone else shared with me, they would appreciate the inputs not being published, since they represent a lot of the work involved in making the puzzles.

**Comment by jfthuong** [comment]
See this post for more details.
https://www.reddit.com/r/adventofcode/wiki/faqs/copyright/inputs/

**Comment by betaveros** [comment]
Hm, yeah, originally I was sort of waiting for AoC to wrap up before going back and purging the input files since there's no way to do it properly without rewriting git history, but I guess I'll just get it over with now...

**Comment by jfthuong** [comment]
By the way, congratulations on your awesome performance and this nice language of yours. Really inspiring!

**Comment by MichalMarsalek** [comment]
Actually, since last year, you are allowed to publish your input but not allowed to collect inputs (see the reddit link above). Before, it was not even allowed to put inputs in a  repo which made far more sense to me tbh.
